//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whole30DietApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingredient
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Store { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] Image { get; set; }
        public string ImageString { get; set; }
        public string Type { get; set; }
        public string Aisle { get; set; }
    }
}
