//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Whole30DietApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public byte[] Image { get; set; }
        public string ImageString { get; set; }
        public string Instructions { get; set; }
        public string QuickInstructions { get; set; }
        public string TotalTime { get; set; }
        public Nullable<int> Rating { get; set; }
        public Nullable<int> Servings { get; set; }
        public string Source { get; set; }
        public string Ingredient1 { get; set; }
        public string Ingredient2 { get; set; }
        public string Ingredient3 { get; set; }
        public string Ingredient4 { get; set; }
        public string Ingredient5 { get; set; }
        public string Ingredient6 { get; set; }
        public string Ingredient7 { get; set; }
        public string Ingredient8 { get; set; }
        public string Ingredient9 { get; set; }
        public string Ingredient10 { get; set; }
        public string Ingredient11 { get; set; }
        public string Ingredient12 { get; set; }
        public string Ingredient13 { get; set; }
        public string Ingredient14 { get; set; }
        public string Ingredient15 { get; set; }
        public string Ingredient16 { get; set; }
        public string Ingredient17 { get; set; }
        public string Ingredient18 { get; set; }
        public string Ingredient19 { get; set; }
        public string Ingredient20 { get; set; }
    }
}
